services:
  app:
    build: .
    image: clientes-api-autenticado:latest
    container_name: clientes-api-autenticado
    restart: always

    environment:
      DB_HOST: db
      DB_NAME: clientes_autenticado_db
      DB_USER: profesor
      DB_PASSWORD: 4688
      DB_PORT: 3306

      VIRTUAL_HOST: clientes-api-autenticado.docker.sulbaranjc.com
      VIRTUAL_PORT: "8000"

    expose:
      - "8000"

    depends_on:
      - db

    networks:
      - nginx-proxy
      - internal

  db:
    image: mariadb:10.6
    container_name: clientes-api-autenticado-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root4688
      MYSQL_DATABASE: clientes_autenticado_db
      MYSQL_USER: profesor
      MYSQL_PASSWORD: 4688

    volumes:
      - db_data:/var/lib/mysql
      - ./docs/init_db.sql:/docker-entrypoint-initdb.d/01_init.sql:ro

    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
  nginx-proxy:
    external: true
